/**
 * @file
 * This is the test bench for LinkedList.c, which is an extension of the list
 * of functions brought forward by LinkedList.h.
 * 
 * The purpose of this file is to test the library for implementing and working with
 * the Linked List data structure.
 * 
 * @auth Nicholas Kuipers
 * 
 * @dateCreated 2/2/2022
 */

#include <stdio.h>
#include <stdlib.h>
#include "LinkedList.h"

//CMPE13 Support Library
#include "BOARD.h"

#ifdef PIC32
// Microchip libraries
#include <xc.h>
#endif


int main(void)
{
    BOARD_Init();
    printf("******Beginning NKuipers' Test Bench for LinkedList.c*****\n");
    /*
     *  ADMINISTRATIVE NOTE: Testing the error generation logic included with every call to malloc() requires the removal or editing of the
     *  size of the heap (unless the function is reiterated many times or an enormous malloc() is called), which generates an error message from the compiler. Due to this,
     *  the test for this error will be commented out in Test 1 (since only one line needs to be changed), so that, if needed, this can be implemented provided the user
     *  makes the appropriate adjustments for the heap in Project Properties
     */
    
    /*
     *  ***Testing Function: LinkedListNew()
     */
    //Test 1: Standard function call using a char pointer with contents. Also tests that initial pointers are NULL.
    printf("\n==================================================\n");
    printf("Test 1: Generic Call of LinkedListNew()\n");
    char *information1 = "First Set of Data";
    ListItem *test1 = LinkedListNew(information1);
    //if(test1 == NULL)   *UNCOMMENT THIS LINE AND COMMENT NEXT LINE FOR ERROR TESTING OF MALLOC (provided heap is adjusted appropriately)
    if(test1->data == information1 && test1->previousItem == NULL && test1->nextItem == NULL)
        printf("SUCCESS\n");
    else
        printf("FAILURE\n");
    
    //Test 2: Function call using a char pointer with no contents
    printf("\n==================================================\n");
    printf("Test 2: Call of LinkedListNew() without any data value\n");
    char *information2 = NULL;
    ListItem *test2 = LinkedListNew(information2);
    if(test2->data == NULL && test2->previousItem == NULL && test2->nextItem == NULL)
        printf("SUCCESS\n");
    else
        printf("FAILURE\n");
    
    /*
     *  ***Testing Function: LinkedListCreateAfter()
     */
    //Test 3: Standard function call using a new data pointer and the list generated from Test 1 of LinkedListNew()
    printf("\n==================================================\n");
    printf("Test 3: Generic call of LinkedListCreateAfter() to add to list generated by first test\n");
    char *information3 = "Second Set";
    ListItem *test3 = LinkedListCreateAfter(test1, information3);
    if(test3->data == information3 && test3->previousItem == test1 && test1->nextItem == test3)
        printf("SUCCESS\n");
    else
        printf("FAILURE\n");
    
    //Test 4: Adding a new ListItem element to the middle of the test1 linked list ({test1LI, test3LI} -> {test1LI, test4LI, test3LI})
    printf("\n==================================================\n");
    printf("Test 4: Additional element placed in the middle of the test1 Linked List\n");
    char *information4 = "Third Set";
    ListItem *test4 = LinkedListCreateAfter(test1, information4);
    if(test4->data == information4 && test4->previousItem->data == information1 && test4->nextItem->data == information3)
        printf("SUCCESS\n");
    else
        printf("FAILURE\n");
    
    //Test 5: LinkedListCreateAfter() is called with a null pointer, thus essentially creating a new list
    printf("\n==================================================\n");
    printf("Test 5: Test of LinkedListCreateAfter() with a null pointer in the parameters\n");
    char *information5 = "Lone Set";
    ListItem *test5 = LinkedListCreateAfter(NULL, information5);
    if(test5->data == information5 && test5->previousItem == NULL && test5->nextItem == NULL)
        printf("SUCCESS\n");
    else
        printf("FAILURE\n");
    
    /*
     *  ADMINISTRATIVE NOTE: For LinkedListRemove() testing for the success of free() is not easily attainable
     *  since the pointer values do not necessarily change; the memory is simply de-allocated and free to be changed
     *  when called upon. During office hours Prof. McGuire provided me with an alternative: the eFence library in Linux.
     *  I will be using this function to ensure free() is properly employed -- otherwise no code will be present here 
     *  to test that functionality. 
     */
    
    /*
     *  ***Testing Function: LinkedListRemove()
     */
    //Test 6: Using LinkedListRemove() to remove the middle element from the test1 Linked List
    printf("\n==================================================\n");
    printf("Test 6: Removal of middle element (test4) from the Linked List headed by test1:\n");
    char *test6 = LinkedListRemove(test4);      //{test1LI, test4LI, test3LI} -> {test1LI, test3LI}
    /*
     *  if statement tests:
     *      -test1 and test 3 now point to one-another
     *      -test6 (char *) has the data from the deleted element
     */
    if(test1->nextItem == test3 && test3->previousItem == test1 && test6 == information4)
        printf("SUCCESS\n");
    else
        printf("FAILURE\n");
    
    //Test 7: Using LinkedListRemove() to remove the first element from the aforementioned linked list
    printf("\n==================================================\n");
    printf("Test 7: Removal of first element from the Linked List:\n");
    char *test7 = LinkedListRemove(test1);      //{test1LI, test3LI} -> {test3LI}
    /*
     *  if statement tests:
     *      -test3 is alone and points to no other element
     *      -test7 (char *) has the data from the deleted element
     */
    if(test3->previousItem == NULL && test3->nextItem == NULL && test7 == information1)
        printf("SUCCESS\n");
    else
        printf("FAILURE\n");
    
     /*
     *  ***Testing Function: LinkedListSize()
     */
    //Test 8: Standard Function call for LinkedListSize() returning the size of a list with elements
    printf("\n==================================================\n");
    printf("Test 8: LinkedListSize() on a linked list with elements:\n");
    //First we need to supply more elements to our previous linked list
    ListItem *test8_1 = LinkedListCreateAfter(test3, "Eighth Go");
    ListItem *test8_2 = LinkedListCreateAfter(test3, "Ninth too");
    //Our linked list is now 3 in size with {test3, test8_2, test8_1}
    //Let's run the LinkedListSize() function on test8_2
    int listSize_test8 = LinkedListSize(test8_2);
    
    if(listSize_test8 == 3)
        printf("SUCCESS\n");
    else
        printf("FAILURE\n");
    
    //Test 9: Function call for LinkedListSize() on a list with one element
    printf("\n==================================================\n");
    printf("Test 9: LinkedListSize() on a linked list with one element:\n");
    //test5 is a LinkedList element that stands on its own
    int listSize_test9 = LinkedListSize(test5);
    
    if(listSize_test9 == 1)
        printf("SUCCESS\n");
    else
        printf("FAILURE\n");
    
    //Test 10: Function call for LinkedListSize() on a list with no elements (a NULL pointer)
    printf("\n==================================================\n");
    printf("Test 10: LinkedListSize() on a linked list with no elements:\n");
    //test5 is a LinkedList element that stands on its own
    int listSize_test10 = LinkedListSize(NULL);
    
    if(listSize_test10 == 0)
        printf("SUCCESS\n");
    else
        printf("FAILURE\n");
    
    /*
     *  ***Testing Function: LinkedListGetFirst()
     */
    //Test 11: Standard function call for LinkedListGetFirst() on a list with elements
    printf("\n==================================================\n");
    printf("Test 11: LinkedListGetFirst() on a linked list with elements:\n");
    //recall we have {test3, test8_2, test8_1}
    ListItem *test11 = LinkedListGetFirst(test8_1);

    if(test11 == test3)
        printf("SUCCESS\n");
    else
        printf("FAILURE\n");
    
    //Test 12: Function call for LinkedListGetFirst() on a list with no elements (NULL pointer)
    printf("\n==================================================\n");
    printf("Test 12: LinkedListGetFirst() on a linked list with NO elements:\n");
    ListItem *test12 = LinkedListGetFirst(NULL);

    if(test12 == NULL)
        printf("SUCCESS\n");
    else
        printf("FAILURE\n");
    
    /*
     *  ***Testing Function: LinkedListGetLast()
     */
    //Test 13: Standard function call for LinkedListGetFirst() on a list with elements
    printf("\n==================================================\n");
    printf("Test 13: LinkedListGetLast() on a linked list with elements:\n");
    //recall we have {test3, test8_2, test8_1}
    ListItem *test13 = LinkedListGetLast(test3);

    if(test13 == test8_1)
        printf("SUCCESS\n");
    else
        printf("FAILURE\n");
    
    //Test 14: Function call for LinkedListGetLast() on a list with no elements (NULL pointer)
    printf("\n==================================================\n");
    printf("Test 14: LinkedListGetLast() on a linked list with NO elements:\n");
    ListItem *test14 = LinkedListGetLast(NULL);

    if(test14 == NULL)
        printf("SUCCESS\n");
    else
        printf("FAILURE\n");
    
    /*
     *  ***Testing Function: LinkedListPrint()
     */
    //Test 15: Function call for LinkedListPrint() on our list with three elements
    printf("\n==================================================\n");
    printf("Test 15: LinkedListPrint() on a linked list with elements:\n");
    //recall we have {test3, test8_2, test8_1}
    int test15 = LinkedListPrint(test8_2);
    /*
     *  test3->data = "Second Set"
     *  test8_2->data = "Ninth too"
     *  test8_1->data = "Eighth Go"
     */

    if(test15 == SUCCESS)
        printf("SUCCESS\n");
    else
        printf("FAILURE\n");
    
    //Test 16: Function call for LinkedListPrint() for a list with no elements (NULL pointer)
    printf("\n==================================================\n");
    printf("Test 16: LinkedListPrint() on a linked list with NO elements:\n");
    //recall we have {test3, test8_2, test8_1}
    int test16 = LinkedListPrint(NULL);

    if(test16 == STANDARD_ERROR)
        printf("SUCCESS\n");
    else
        printf("FAILURE\n");
    
    /*
     *  ***Testing Function: LinkedListSwapData()
     */
    //Test 17: Function Call for LinkedListSwapData() on two ListItem elements
    printf("\n==================================================\n");
    printf("Test 17: LinkedListSwapData() on two ListItem elements:\n");
    //First we print the original values for {test3, test8_2, test8_1}
    printf("Original set of values: ");
    LinkedListPrint(test3);
    printf("Set of values after second and third elements swapped: ");
    int test17 = LinkedListSwapData(test8_2, test8_1);
    LinkedListPrint(test3);

    if(test17 == SUCCESS)
        printf("SUCCESS\n");
    else
        printf("FAILURE\n");
    
    //Test 18: Function Call for LinkedListSwapData() on two ListItem elements where one element is NULL
    printf("\n==================================================\n");
    printf("Test 18: LinkedListSwapData() with a valid element and a NULL element:\n");
    int test18 = LinkedListSwapData(test8_2, NULL);

    if(test18 == STANDARD_ERROR)
        printf("SUCCESS\n");
    else
        printf("FAILURE\n");
    
    BOARD_End();
    while(1);
}


